name: Python Package

on:
  release:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-wheels:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-13
          - macos-14

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.5
      
      - name: Set up Visual Studio shell
        if: runner.os == 'Windows'
        uses: egor-tensin/vs-shell@v2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse bindings/python
        env:
          CIBW_ARCHS_LINUX: x86_64 i686 aarch64
          # musllinux uses apk & manylinux uses yum
          CIBW_BEFORE_BUILD_LINUX: |
            if command -v apk > /dev/null; then
              apk add --update clang && make -C src blst
            elif command -v yum > /dev/null; then
              yum install -y clang && make -C src blst
            fi
          CIBW_ENVIRONMENT_WINDOWS: |
            DISTUTILS_USE_SDK=1 CC=gcc CXX=g++
          CIBW_BEFORE_BUILD_WINDOWS: |
            cd blst && build.bat && cp blst.lib ../lib
            make -C src blst
          CIBW_BEFORE_BUILD_MACOS: |
            make -C src blst


